version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql-mobius
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - /path/to/data/mysql:/var/lib/mysql
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-mobius
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - /path/to/data/mosquitto:/mosquitto/data
