CREATE TABLE IF NOT EXISTS hit (
    ct TEXT PRIMARY KEY,
    http INTEGER DEFAULT 0,
    mqtt INTEGER DEFAULT 0,
    coap INTEGER DEFAULT 0,
    ws INTEGER DEFAULT 0
);

-- lookup (Base Resource Table)
CREATE TABLE IF NOT EXISTS lookup (
  pi TEXT NOT NULL,
  ri TEXT PRIMARY KEY,
  ty INTEGER NOT NULL,
  ct TEXT NOT NULL,
  st INTEGER NOT NULL,
  rn TEXT NOT NULL,
  lt TEXT NOT NULL,
  et TEXT NOT NULL,
  acpi TEXT,
  lbl TEXT,
  at TEXT,
  aa TEXT,
  sri TEXT,
  spi TEXT,
  subl TEXT,
  acpl TEXT
);

-- acp (Access Control Policy)
CREATE TABLE IF NOT EXISTS acp (
  ri TEXT PRIMARY KEY,
  pv TEXT NOT NULL,
  pvs TEXT NOT NULL,
  FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE
);

-- cb (CSEBase)
CREATE TABLE IF NOT EXISTS cb (
  ri TEXT PRIMARY KEY,
  cst TEXT NOT NULL,
  csi TEXT NOT NULL,
  srt TEXT NOT NULL,
  poa TEXT NOT NULL,
  nl TEXT NOT NULL,
  ncp TEXT NOT NULL,
  srv TEXT,
  FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE
);

-- ae (Application Entity)
CREATE TABLE IF NOT EXISTS ae (
  ri TEXT PRIMARY KEY,
  apn TEXT NOT NULL,
  api TEXT NOT NULL,
  aei TEXT NOT NULL,
  poa TEXT NOT NULL,
  "or" TEXT NOT NULL,
  rr TEXT NOT NULL,
  nl TEXT NOT NULL,
  csz TEXT DEFAULT NULL,
  srv TEXT DEFAULT NULL,
  FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE
);

-- cnt (Container)
CREATE TABLE IF NOT EXISTS cnt (
  ri TEXT PRIMARY KEY,
  cr TEXT NOT NULL,
  mni TEXT NOT NULL,
  mbs TEXT NOT NULL,
  mia TEXT NOT NULL,
  cni TEXT NOT NULL,
  cbs TEXT NOT NULL,
  li TEXT NOT NULL,
  "or" TEXT NOT NULL,
  disr TEXT NOT NULL,
  FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE
);

-- cin (ContentInstance)
CREATE TABLE IF NOT EXISTS cin (
  ri TEXT PRIMARY KEY,
  pi TEXT NOT NULL,
  cr TEXT NOT NULL,
  cnf TEXT NOT NULL,
  cs TEXT NOT NULL,
  "or" TEXT NOT NULL,
  con TEXT NOT NULL,
  CONSTRAINT cin_ri FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE,
  CONSTRAINT cin_pi FOREIGN KEY (pi) REFERENCES cnt(ri) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sub (
  ri VARCHAR(200) NOT NULL,
  pi VARCHAR(400) DEFAULT NULL,
  enc VARCHAR(45) DEFAULT NULL,
  exc VARCHAR(45) DEFAULT NULL,
  nu VARCHAR(200) DEFAULT NULL,
  gpi VARCHAR(45) DEFAULT NULL,
  nfu VARCHAR(45) DEFAULT NULL,
  bn VARCHAR(45) DEFAULT NULL,
  rl VARCHAR(45) DEFAULT NULL,
  psn VARCHAR(45) DEFAULT NULL,
  pn VARCHAR(45) DEFAULT NULL,
  nsp VARCHAR(45) DEFAULT NULL,
  ln VARCHAR(45) DEFAULT NULL,
  nct VARCHAR(45) DEFAULT NULL,
  nec VARCHAR(45) DEFAULT NULL,
  cr VARCHAR(45) DEFAULT NULL,
  su VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (ri),
  CONSTRAINT sub_ri FOREIGN KEY (ri) REFERENCES lookup(ri) ON DELETE CASCADE
);
